# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = false

# Mod Properties
mod.version = 0.1.12
mod.group = com.trainguy9512
mod.id = locomotion

mod.name = Locomotion
mod.description = An animation overhaul mod
mod.license = GPLv3

loom.ignoreDependencyLoomVersionValidation=true

# Fabric Loader (only used by the shared Architectury common project to get Mixin on its classpath; Fabric itself is not supported)
version.1_21_1.fabric_loader = 0.16.10
version.1_21_11.fabric_loader = 0.18.4
version.1_21_10.fabric_loader = 0.17.2
version.1_21_8.fabric_loader = 0.16.10
version.1_21_5.fabric_loader = 0.16.10
version.1_21_4.fabric_loader = 0.16.10

# Forge Loader
#version.1_21_8.forge_loader = 58.0.1
#version.1_21_5.forge_loader = 55.0.3
#version.1_21_4.forge_loader = 54.1.0

# NeoForge Loader
version.1_21_1.neoforge_loader = 21.1.234
version.1_21_11.neoforge_loader = 21.11.0-beta
version.1_21_10.neoforge_loader = 21.10.47-beta
version.1_21_8.neoforge_loader = 21.8.23
version.1_21_5.neoforge_loader = 21.5.0-beta
version.1_21_4.neoforge_loader = 21.4.124

# Parchment Minecraft versions
version.1_21_1.parchment_minecraft_version = 1.21.1
version.1_21_11.parchment_minecraft_version = 1.21.10
version.1_21_10.parchment_minecraft_version = 1.21.10
version.1_21_8.parchment_minecraft_version = 1.21.6
version.1_21_5.parchment_minecraft_version = 1.21.4
version.1_21_4.parchment_minecraft_version = 1.21.4

# Parchment mapping versions
version.1_21_1.parchment_mappings_version = 2024.11.17
version.1_21_11.parchment_mappings_version = 2025.10.12
version.1_21_10.parchment_mappings_version = 2025.10.12
version.1_21_8.parchment_mappings_version = 2025.06.29
version.1_21_5.parchment_mappings_version = 2025.03.23
version.1_21_4.parchment_mappings_version = 2025.03.23

# Yet Another Light Minecraft Mappings versions
version.1_21_11.yalmm = yalmm:25w45a+build.7
#version.1_21_11.yalmm = yalmm:1.21.11+build.3
version.1_21_10.yalmm = yalmm-mojbackward:1.21.10+build.3
version.1_21_8.yalmm = yalmm-mojbackward:1.21.8+build.3
version.1_21_5.yalmm = yalmm-mojbackward:1.21.5+build.3
version.1_21_4.yalmm = yalmm-mojbackward:1.21.4+build.3


# YACL
version.1_21_1.yacl_version = 3.7.1+1.21.1
version.1_21_11.yacl_version = 3.8.1+1.21.11
version.1_21_10.yacl_version = 3.8.0+1.21.9
version.1_21_8.yacl_version = 3.7.1+1.21.6
version.1_21_5.yacl_version = 3.6.6+1.21.5
version.1_21_4.yacl_version = 3.6.6+1.21.4




# I see my armored hand